global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging.Testing;
global using NSubstitute;
global using NSubstitute.ExceptionExtensions;
global using NUnit.Framework;
global using PhotoManager.Common;
global using PhotoManager.Domain;
global using PhotoManager.Domain.Interfaces;
global using PhotoManager.Domain.UserConfigurationSettings;
global using PhotoManager.Infrastructure;
global using PhotoManager.Infrastructure.Database;
global using PhotoManager.Infrastructure.Database.Storage;
global using PhotoManager.Infrastructure.TablesConfig;
global using PhotoManager.Tests.Integration.Infrastructure.AssetRepositoryTests;
global using PhotoManager.UI.Converters;
global using PhotoManager.UI.ViewModels;
global using System.IO;
global using Rotation = PhotoManager.Common.ImageRotation;
